In [1]:
import numpy as np

In [2]:
def simplify(a, b):
    if a + b <= 1:
        c = np.random.choice([0, 1], p=[a / (a + b), b / (a + b)])
        return [a + b, 0] if c == 0 else [0, a + b]
    elif 1 < a + b < 2:
        c = np.random.choice([0, 1], p=[(1 - b) / (2 - a - b), (1 - a) / (2 - a - b)])
        return [1, a + b - 1] if c == 0 else [a + b - 1, 1]
def depround(x):
    while (True):
        not_rounded = np.where(np.logical_and(x < 1, x > 0))[0]
        if len(not_rounded) == 0:
            break
        print(not_rounded, x)
        i, j = not_rounded[:2]
        x[i], x[j] = simplify(x[i], x[j])
    return x
def partition_matroid_round(x, sets_S):
    for S in sets_S:
        x[S] = depround(x[S])
    return x

In [5]:
x = np.array([.3, .2, 1, 0, .3, .2])
partition_matroid_round(x, [list(range(x.size))])

[0 1 4 5] [0.3 0.2 1.  0.  0.3 0.2]
[0 4 5] [0.5 0.  1.  0.  0.3 0.2]
[0 5] [0.8 0.  1.  0.  0.  0.2]


array([0., 0., 1., 0., 0., 1.])